clear all; clc;
global global_info; % user data
global_info.START_AT = [7 0 0]; %simulation starts at 7 in the morning
global_info.DELTA_TIME = 60;
global_info.STOP_AT = [23 00 0]; %simulation starts at 11 in the evening
global_info.barge_capacity = 10; %capacity in m3
global_info.road_kuneset_lervik_capacity = 4; %capacity of barges on road each way
global_info.dumped_at_lervik = 0;

pns = pnstruct('lervik_pn_pdf'); % create petri net structure

dyn.m0 = {'pStorageAtKuneset',690/global_info.barge_capacity,...
          'pTransportVehicles',global_info.road_kuneset_lervik_capacity,...
          'pEnroute',0,...
          'pDumpAtLervik',0,...
          'pVehiclesEnrouteBack',0,...
          };
dyn.ft = {'tNewVehicleAvailable',1,...
          'tStartTransport',1,...
          'tDumpMass',1,...
          'tStatusReportGenerator',1,...
          }; 
      
prnsys(pns, dyn);
pni = initialdynamics(pns, dyn);
sim = gpensim(pni); % perform simulation runs

plotp(sim, {...
'pDumpAtLervik',...
'pEnroute',...
'pStorageAtKuneset',...
'pVehiclesEnrouteBack',...
'pTransportVehicles',...
}); % plot the results

fprintf('amount dumped today: %s\n', num2str(global_info.dumped_at_lervik));
