clear all; clc;
global global_info; % user data
global_info.START_AT = [7 0 0]; %simulation starts at 7 in the morning
global_info.DELTA_TIME = 60;
global_info.STOP_AT = [23 00 0]; %simulation starts at 11 in the evening
global_info.generated_mass_kuneset = 0; %generated mass in m3
global_info.truck_capacity = 5; %capacity in m3
global_info.mass_per_blast = 110;
global_info.road_kuneset_fiskaa_capacity = 7; %capacity of trucks on road each way
global_info.dumped_at_fiskaa = 0;

pns = pnstruct('fiskaa_pn_pdf'); % create petri net structure

dyn.m0 = {'pStorageAtKuneset',0,...
          'pTransportVehicles',global_info.road_kuneset_fiskaa_capacity,...
          'pEnroute',0,...
          'pDumpAtFiskaa',0,...
          'pVehiclesEnrouteBack',0,...
          };
dyn.ft = {'tMassGenerator',1,...
          'tNewVehicleAvailable',1,...
          'tStartTransport',1,...
          'tDumpMass',1,...
          'tStatusReportGenerator',1,...
          }; 
      
prnsys(pns, dyn);
pni = initialdynamics(pns, dyn);
sim = gpensim(pni); % perform simulation runs

plotp(sim, {...
'pDumpAtFiskaa',...
'pEnroute',...
'pStorageAtKuneset',...
'pVehiclesEnrouteBack',...
'pTransportVehicles',...
}); % plot the results

fprintf('amount dumped today: %s\n', num2str(global_info.dumped_at_fiskaa));
