function [pns] = Buoey_pn_pdf()
pns.PN.name = ‘Buoey’;

pns.set_of_Ps = {...
‘pStorageAtBuoey’,...
’pBelt’,...
’pStorageAtRosenberg’}:

pns.set_of_Ts = {‘tMassGenerator’,’tLoadOntoConveyorBelt,’tCrushMass’};

pns.set_of_As = {...
‘tMassGenerator’,‘pStorageAtBuoey’,<insert value>,...
‘pStorageAtBuoey’,’tLoadOntoConveyorBelt,<insert value>,...
’tLoadOntoConveyorBelt,’pBelt’,<insert value>,...
’pBelt’,’tCrushMass’,<insert value>,...
’tCrushMass’,’pStorageAtRosenberg’<insert value>};