function [pns] = solbakk_pn_pdf()
pns.PN.name = 'Solbakk';

pns.set_of_Ps = {...
'pStorageAtSolbakk',...
'pBelt',...
'pStorageAtSolbakk_sea'};

pns.set_of_Ts = {'tMassGenerator','tLoadOntoConveyorBelt','tCrushMass'};

pns.set_of_As = {...
'tMassGenerator','pStorageAtSolbakk',1,...
'pStorageAtSolbakk','tLoadOntoConveyorBelt',1,...
'tLoadOntoConveyorBelt','pBelt',1,...
'pBelt','tCrushMass',1,...
'tCrushMass','pStorageAtSolbakk_sea',1};
