function [pns] = Solbakk_pn_pdf()
pns.PN.name = ‘Solbakk’;

pns.set_of_Ps = {...
‘pStorageAtSolbakk’,...
’pBelt’,...
’pStorageAtSolbakk_sea’}:

pns.set_of_Ts = {‘tMassGenerator’,’tLoadOntoConveyorBelt,’tCrushMass’};

pns.set_of_As = {...
‘tMassGenerator’,‘pStorageAtSolbakk’,<insert value>,...
‘pStorageAtSolbakk’,’tLoadOntoConveyorBelt,<insert value>,...
’tLoadOntoConveyorBelt,’pBelt’,<insert value>,...
’pBelt’,’tCrushMass’,<insert value>,...
’tCrushMass’,’pStorageAtSolbakk_sea’<insert value>};