clear all; clc; 
user_init()
global ryfast_info;
global global_info; % user data
global_info.REAL_TIME = 1;
ryfast_info.start_time = current_clock(1);
global_info.STOP_AT = current_clock(1)+300;
%global_info.PRINT_LOOP_NUMBER = 1; 
%global_info.MAX_LOOP = 1;

pns = pnstruct('tasta_pn_pdf'); % create petri net structure

dyn.m0 = {'pStorageAtTasta',20,...
          'pTransportVehicles',ryfast_info.road_tasta_hinna_capacity/2,...
          'pEnroute',0,...
          'pDumpAtJaatta',0,...
          'pVehiclesEnrouteBack',ryfast_info.road_tasta_hinna_capacity/2
          };
dyn.ft = {'tMassGenerator',90,...
          'tNewVehicleAvailable',11,...
          'tStartTransport',3,...
          'tDumpMass',11,...
          'tStatusReportGenerator',60,...
          }; 
      
%dyn.ip = {'tStartTransport',5};

prnsys(pns, dyn);
pni = initialdynamics(pns, dyn);

sim = gpensim(pni); % perform simulation runs

plotp(sim, {...
'pStorageAtTasta',...
'pEnroute',...
'pVehiclesEnrouteBack',...
'pDumpAtJaatta',...
}); % plot the results

fprintf('amount dumped: %s\n', num2str(ryfast_info.dumped_at_jaattaa));
