clear all; clc; 
user_init()
global ryfast_info;
global global_info; % user data
global_info.START_AT = [7 0 0];
global_info.DELTA_TIME = 60;
global_info.STOP_AT = [23 00 0];
%global_info.PRINT_LOOP_NUMBER = 1; 
%global_info.MAX_LOOP = 1;

pns = pnstruct('tasta_pn_pdf'); % create petri net structure

dyn.m0 = {'pStorageAtTasta',200/ryfast_info.truck_capacity,...
          'pTransportVehicles',ryfast_info.road_tasta_hinna_capacity,...
          'pEnroute',0,...
          'pDumpAtJaatta',0,...
          'pVehiclesEnrouteBack',0,...
          };
dyn.ft = {'tMassGenerator',1,...
          'tNewVehicleAvailable',1,...
          'tStartTransport',1,...
          'tDumpMass',1,...
          'tStatusReportGenerator',1,...
          }; 
      

priorset('tStartTransport', 10);

prnsys(pns, dyn);
pni = initialdynamics(pns, dyn);
ryfast_info.start_time = current_time();
sim = gpensim(pni); % perform simulation runs

plotp(sim, {...
'pStorageAtTasta',...
'pEnroute',...
'pVehiclesEnrouteBack',...
'pTransportVehicles',...
}); % plot the results

fprintf('amount dumped: %s\n', num2str(ryfast_info.dumped_at_jaattaa));
