function [pns] = buoey_pn_pdf()
pns.PN.name = 'Buoey';

pns.set_of_Ps = {...
'pStorageAtBuoey',...
'pBelt',...
'pStorageAtRosenberg'};

pns.set_of_Ts = {'tMassGenerator','tLoadOntoConveyorBelt','tCrushMass'};

pns.set_of_As = {...
'tMassGenerator','pStorageAtBuoey',1,...
'pStorageAtBuoey','tLoadOntoConveyorBelt',1,...
'tLoadOntoConveyorBelt','pBelt',1,...
'pBelt','tCrushMass',1,...
'tCrushMass','pStorageAtRosenberg',1};
