clear all; clc;
global global_info; % user data
global_info.START_AT = [7 0 0]; %simulation starts at 7 in the morning
global_info.DELTA_TIME = 60;
global_info.STOP_AT = [23 00 0]; %simulation starts at 11 in the evening
global_info.mass_per_blast = 55;
global_info.generated_mass_buoey = 0; %generated mass in m3
global_info.belt_capacity = 1; %capacity in m3/load
global_info.dumped_at_rosenberg = 0;

pns = pnstruct('buoey_pn_pdf'); % create petri net structure

dyn.m0 = {...
    'pStorageAtBuoey',global_info.mass_per_blast,...
    'pBelt',0,...
    'pDumpAtRosenberg',0};
dyn.ft = {...
    'tMassGenerator',10800,...
    'tLoadOntoConveyorBelt',180,...
    'tCrushMass',1,...
    'tStatusReportGenerator',1,...
    }; 

pni = initialdynamics(pns, dyn);
sim = gpensim(pni); % perform simulation runs
global_info.generated_mass_buoey = global_info.generated_mass_buoey - global_info.mass_per_blast;

plotp(sim, {...
    'pStorageAtBuoey',...
    'pBelt',...
    }); % plot the results
fprintf('amount generated today: %s\n', num2str(global_info.generated_mass_buoey));
fprintf('amount dumped today: %s\n', num2str(global_info.dumped_at_rosenberg));
